const WELCOME_ID = 'WELCOME_ELEMENT'
const EXPERIENCE_ID = 'EXPERIENCE_ELEMENT'
const PROJECTS_ID = 'PROJECTS_ELEMENT'
const SKILLS_ID = 'SKILLS_ELEMENT'

export {
    WELCOME_ID,
    EXPERIENCE_ID,
    PROJECTS_ID,
    SKILLS_ID
}